Update integration workflow

diff --git a/.github/workflows/test-integration.yml b/.github/workflows/test-integration.yml
--- a/.github/workflows/test-integration.yml
+++ b/.github/workflows/test-integration.yml
@@ -2,11 +2,11 @@ name: Integration Test
 
 # Incrementally comprehensive based on the type of change:
 #
-# | Type   | Description           | Test Runs                                 |
-# |--------|-----------------------|-------------------------------------------|
-# | base   | Source code PRs       | Chromium (Node 24)                        |
-# | normal | @react-router/dev PRs | + Firefox/Webkit/Edge (n24), Chromium (n22) |
-# | full   | Commits on `main`     | + Firefox/Webkit (n22)                     |
+# | Type   | Description            | Test Runs                                   |
+# |--------|------------------------|---------------------------------------------|
+# | base   | Non-docs and draft PRs | Chromium (Node 24).                         |
+# | normal | @react-router/dev PRs  | + Firefox/Webkit/Edge (n24), Chromium (n22) |
+# | full   | Commits on `main`      | + Firefox/Webkit (n22)                      |
 
 on:
   push:
@@ -53,13 +53,21 @@ jobs:
         env:
           GH_TOKEN: ${{ github.token }}
           PR_NUMBER: ${{ github.event.pull_request.number }}
+        # If `gh pr diff` exits with a non-zero code, it might be because the PR
+        # has >300 files, or it could be for any number of unknown reasons.  If
+        # that happens take the conservative route and run the larger `dev` suite.
         run: |
           if [ "${{ github.event_name }}" = "push" ]; then
             echo "type=full" >> "$GITHUB_OUTPUT"
-          elif gh pr view "$PR_NUMBER" --json files -q '.files[].path' | grep -q '^packages/react-router-dev/'; then
-            echo "type=dev" >> "$GITHUB_OUTPUT"
-          else
+          elif [ "${{ github.event.pull_request.draft }}" = "true" ]; then
             echo "type=base" >> "$GITHUB_OUTPUT"
+          else
+            OUTPUT=$(gh pr diff "$PR_NUMBER" --name-only)
+            if [ $? != 0 ] || echo "$OUTPUT" | grep -q '^packages/react-router-dev/'; then
+              echo "type=dev" >> "$GITHUB_OUTPUT"
+            else
+              echo "type=base" >> "$GITHUB_OUTPUT"
+            fi
           fi
 
   # base only runs Node 24/Chromium
